### ISSUE TITLE
Remove use of missing type StaticAssemblyProvider

### ISSUE THREAD

**Issue by DavidObando** [aspnet/Performance#116]
Change aspnet/Mvc@f638c05 removed type StaticAssemblyProvider and changed the way DNX works to use application parts. This breaks compilation of [test\TestApp.Test](https://github.com/aspnet/Performance/tree/dev/test/TestApp.Test).

/cc @javiercn @NTaylorMullen

**Comment by javiercn** [comment]
I’ll take a look

**Comment by DavidObando** [comment]
Addressed by #133
