### ISSUE TITLE
Newtonsoft.Json version conflict at runtime

### ISSUE THREAD

**Issue by DavidObando** [aspnet/Performance#118]
Project test/TestApp.Test is throwing at runtime due to Microsoft.Extensions.DependencyModel requiring Newtonsoft.Json version 7.0.1, while the project is using version 8.x. Issue dotnet/cli#1233 tracks the version change required for these tests to work again.

```
    MvcBenchmarks.InMemory.LocalizedViewsTest.LocalizedViews_TagHelpers [FAIL]
      System.IO.FileNotFoundException : Could not load file or assembly 'Newtonsoft.Json, Version=7.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The system cannot find the file specified.
      Stack Trace:
           at Microsoft.Extensions.DependencyModel.DependencyContextJsonReader.Read(Stream stream)
           at Microsoft.Extensions.DependencyModel.DependencyContextLoader.LoadAssemblyContext(Assembly assembly)
           at Microsoft.Extensions.DependencyModel.DependencyContextLoader.Load(Assembly assembly)
           at Microsoft.AspNetCore.Mvc.Razor.Internal.DependencyContextRazorViewEngineOptionsSetup.ConfigureRazor(RazorViewEngineOptions options, IHostingEnvironment hostingEnvironment)
           at Microsoft.Extensions.Options.OptionsCache`1.CreateOptions()
           at System.Threading.LazyInitializer.EnsureInitializedCore[T](T& target, Boolean& initialized, Object& syncLock, Func`1 valueFactory)
           at Microsoft.Extensions.Options.OptionsCache`1.get_Value()
           at Microsoft.AspNetCore.Mvc.Razor.Internal.DefaultRazorViewEngineFileProviderAccessor..ctor(IOptions`1 optionsAccessor)
```

When I force the executing project to load Newtonsoft.Json version 7.0.1, I get a different exception:
```
      ---- System.IO.FileNotFoundException : Could not load file or assembly 'Newtonsoft.Json, Version=8.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The system cannot find the file specified.
      Stack Trace:
           at MvcBenchmarks.InMemory.BasicApiTest..ctor()
        ----- Inner Stack Trace -----
           at Microsoft.Extensions.Configuration.Json.JsonConfigurationProvider.Load(Stream stream)
           at Microsoft.Extensions.Configuration.FileConfigurationProvider.Load()
           at Microsoft.Extensions.Configuration.ConfigurationBuilder.Build()
        D:\GitHub\aspnet\Performance\testapp\BasicApi\Startup.cs(27,0): at BasicApi.Startup..ctor(IHostingEnvironment hosting, IApplicationEnvironment applicationEnvironment)
```

**Comment by DavidObando** [comment]
@Eilon seeing you foresaw issues like this one when you logged dotnet/cli#1233, what do you think we can do in the meantime to get unblocked?

/cc @sivagms

**Comment by Eilon** [comment]
Hmm, why is this only causing an error in your case? Wouldn't the same issue prevent any ASP.NET Core app from working? What are the differences?

**Comment by DavidObando** [comment]
The issue went away, closing.

**Comment by DavidObando** [comment]
Oh, spoke too soon. It's still there.

**Comment by davidfowl** [comment]
Something isn't right. What @Eilon said makes sense. This app shouldn;t be special unless something was explicitly downgrading to 7.0.1 and dotnet restore would tell you if that was the case.

**Comment by DavidObando** [comment]
I'm currently investigating.

**Comment by davidfowl** [comment]
@DavidObando use the lock file 😄

**Comment by DavidObando** [comment]
According to my lock file, this dependency chain leads to 7.0.1:
```
Microsoft.AspNetCore.Mvc/1.0.0-rc3-20553 depends on
Microsoft.AspNetCore.Mvc.ApiExplorer/1.0.0-rc3-20553 depends on
Microsoft.AspNetCore.Mvc.Core/1.0.0-rc3-20553 depends on
Microsoft.Extensions.DependencyModel/1.0.0-rc2-002353 depends on
Newtonsoft.Json/7.0.1
```

While this one leads to 8.0.3:
```
Microsoft.AspNetCore.Mvc/1.0.0-rc3-20553 depends on
Microsoft.AspNetCore.Mvc.Razor/1.0.0-rc3-20553 depends on
Microsoft.AspNetCore.Mvc.ViewFeatures/1.0.0-rc3-20553 depends on
Microsoft.AspNetCore.Mvc.Formatters.Json/1.0.0-rc3-20553 depends on
Microsoft.AspNetCore.JsonPatch/1.0.0-rc3-20553 depends on
Newtonsoft.Json/8.0.3
```

The project is `test\TestApp.Test` which aggregates some of the apps under `testapp` by referencing them as dependencies, and then instantiates them as test servers.

I'm not sure if this was happening before or not, since this repo isn't really building. I stumbled upon this in [a branch I have](https://github.com/aspnet/Performance/tree/daobando/testfixes) that's actually able to build and starts running the tests.

**Comment by Eilon** [comment]
You have RC2 and RC3 packages in the first example. MS.Extensions.DependencyModel is RC2, but everything else is RC3. Can't mix those.

**Comment by DavidObando** [comment]
Is there a way to control the RC2 vs RC3 issue? My project just wants to pull `"Microsoft.AspNetCore.Mvc": "1.0.0-*"`, those dependencies are what I'm being served by the feeds. I tried cleaning my nuget caches, and also in a clean machine, got the same results every time.

**Comment by Eilon** [comment]
You might have `aspnetvnext` or `aspnetcidev` in your feed list, which has RC3 (this will be RTM). You need to use a release feed if you want RC2, or a dev feed if you want RC3/RTM.

**Comment by DavidObando** [comment]
The project was mixing netcoreapp1.0 with DNX. DNX! Dismiss this.

**Comment by pantonis** [comment]
I have the same problem now. 
Using asp.net core rc2 (.NET Framework) and a windows class library.

This is a link to a test project 

https://github.com/pantonis/AspNetRC2EFCore

**Comment by Eilon** [comment]
@pantonis can you provide more info about what you're seeing? Can you run `dotnet --version` and show us what you see?

**Comment by pantonis** [comment]
1.0.0-preview1-002702

**Comment by pantonis** [comment]
and this is where I find the dependency in the project.lock.json

```JSON
 "Microsoft.DotNet.ProjectModel/1.0.0-rc2-002702": {
        "type": "package",
        "dependencies": {
          "Microsoft.Extensions.DependencyModel": "1.0.0-rc2-002702",
          "Newtonsoft.Json": "7.0.1",
          "NuGet.Packaging": "3.5.0-beta-final",
          "NuGet.RuntimeModel": "3.5.0-beta-final",
          "System.Reflection.Metadata": "1.3.0-rc2-24027"
        },
        "compile": {
          "lib/net451/Microsoft.DotNet.ProjectModel.dll": {}
        },
        "runtime": {
          "lib/net451/Microsoft.DotNet.ProjectModel.dll": {}
        }
      },

 "Microsoft.Extensions.DependencyModel/1.0.0-rc2-final": {
        "type": "package",
        "dependencies": {
          "Microsoft.DotNet.InternalAbstractions": "1.0.0-rc2-002702",
          "Newtonsoft.Json": "7.0.1"
        },
        "compile": {
          "lib/net451/Microsoft.Extensions.DependencyModel.dll": {}
        },
        "runtime": {
          "lib/net451/Microsoft.Extensions.DependencyModel.dll": {}
        }
      },
```

**Comment by Eilon** [comment]
What is in your project.json? So far I think that project.lock.json looks fine - everything is using NewtonSoft.Json 7.0.1.

**Comment by pantonis** [comment]
https://onedrive.live.com/redir?resid=74B6542FA94FAF9E!1599&authkey=!AMAwXQ6VXCCLzJo&ithint=folder%2cjson

**Comment by pantonis** [comment]
@Eilon you can see the code here. This repo reproduces the problem. https://github.com/pantonis/AspNetRC2EFCore

**Comment by Eilon** [comment]
@pantonis thanks for sharing the app.

What happens if you update the class lib at https://github.com/pantonis/AspNetRC2EFCore/blob/master/ClassLibrary1/packages.config to point to Newtonsoft.Json 8.0.3? I'm just wondering if that makes the issue go away.

**Comment by pantonis** [comment]
No same error.

**Comment by Eilon** [comment]
@pantonis I'm assuming this is the same issue from https://github.com/aspnet/Mvc/issues/4680 ? If so, I'm closing this issue here and we'll continue the discussion in the other issue. Thanks!

**Comment by pantonis** [comment]
Yes it is thanks
