### ISSUE TITLE
Roslyn libraries out of sync

### ISSUE THREAD

**Issue by shhsu** [aspnet/Performance#127]
Currently NetCore runtime resolves to "Microsoft.NETCore.App/1.0.0-rc2-24008" which uses an older version of Roslyn libraries. This is causing Microsoft.CodeAnalysis.CSharp.dll and Microsoft.CodeAnalysis.dll being copied over even if shared framework is specified in user app. This will slow down user's app start up.

      "Microsoft.NETCore.App/1.0.0-rc2-24008": {
        "type": "package",
        "dependencies": {
          "Microsoft.CodeAnalysis.CSharp": "1.3.0-beta1-20160321-04",
         ....
     }

it uses an older version than what razor is using:

"Microsoft.AspNetCore.Mvc.Razor/1.0.0-rc2-20587": {
        "type": "package",
        "dependencies": {
          "Microsoft.CodeAnalysis.CSharp": "1.3.0-beta1-20160410-01",
      ...
      }

**Comment by JunTaoLuo** [comment]
Will be fixed in https://github.com/aspnet/CoreCLR/pull/96
