### ISSUE TITLE
Use IISIntegration Tools

### ISSUE THREAD

**Issue by DavidObando** [aspnet/Performance#153]
Currently we have issues when publishing for use in IIS. Net451 creates a non portable EXE file, while netcoreapp1.0 creates a portable, shared-runtime DLL. That means that `web.config` isn't the same on both scenarios.

IISIntegration Tools can help address this. It will generate the correct values for the `web.config` when publishing. It does have a limitation: it assumes that `web.config` lives in the root of the project, while most of our projects have a `web.config` living under `wwwroot`.

Currently our web.config reads something like:

``` XML
<?xml version="1.0"?>
<configuration>
  <system.webServer>
    <aspNetCore forwardWindowsAuthToken="true" processPath="dotnet.exe" arguments="..\BasicKestrel.dll" stdoutLogEnabled="true" stdoutLogFile=".\stdout.log" />
    <handlers>
      <add name="aspNetCore" path="*" verb="*" modules="AspNetCoreModule" resourceType="Unspecified"/>
    </handlers>
  </system.webServer>
</configuration>
```

The fix consists of three steps for each project that has a `web.config` file.
Step 1: Move `web.config` out of `wwwroot` into the root of the project. Then edit to read like this:

``` XML
<?xml version="1.0"?>
<configuration>
  <system.webServer>
    <aspNetCore forwardWindowsAuthToken="true" processPath="%LAUNCHER_PATH%" arguments="%LAUNCHER_ARGS%" stdoutLogEnabled="true" stdoutLogFile=".\stdout.log" />
    <handlers>
      <add name="aspNetCore" path="*" verb="*" modules="AspNetCoreModule" resourceType="Unspecified"/>
    </handlers>
  </system.webServer>
</configuration>
```

Step 2: Add IISIntegration Tools to project.json:

``` JSON
  "tools": {
    "Microsoft.AspNetCore.Server.IISIntegration.Tools": "1.0.0-*"
  },
  "scripts": {
    "postpublish": "dotnet publish-iis --publish-folder %publish:OutputPath% --framework %publish:FullTargetFramework%"
  }
```

Step 3: Change automation to pick up the `web.config` from the root of the project as opposed to `wwwroot`.

Alternatively, if IISIntegration Tools is not what we want, we could have two different `web.config` files in each project under `wwwroot` (one for each framework), and the `"postpublish"` process can choose the correct one and copy it to the right location.

@sivagms

**Comment by moozzyk** [comment]
you can also:
 - write your own tool by copying publish-iis and changing the behavior 
 - create a post-postpublish step where you copy the web.config to the right location and fix paths
 - update the publish-iis tool to take an optional parameter which would be the path to put the web.config which would be relative to the approot and take it into account when publishing. (I kind of thought about this since the hardcoded target path is inconvenient in some cases)

**Comment by aspnet-hello** [comment]
We are closing all the issues in this repo because this repo is no longer in used. Please see the README in this repo for more information.
