### ISSUE TITLE
Add feature to profile the runs on Measure.sh

### ISSUE THREAD

**Issue by shhsu** [aspnet/Performance#155]
In https://github.com/aspnet/Performance/blob/dev/test/ColdStart/Measure.ps1, we have option to profile the runs with wpr or perfview. https://github.com/aspnet/Performance/blob/dev/test/ColdStart/Measure.sh should have similar option. Example of how to do this is in https://github.com/aspnet/Performance/blob/dev/test/ColdStart/PerformTestAndProfile.sh - we should merge the logic in the Measure.sh and remove the script

**Comment by aspnet-hello** [comment]
We are closing all the issues in this repo because this repo is no longer in used. Please see the README in this repo for more information.
