### ISSUE TITLE
Test Apps do not stop when profiling with -wpr option

### ISSUE THREAD

**Issue by shhsu** [aspnet/Performance#156]
When running test/ColdStart/Measure.ps1 with WPR option, test apps are not properly closed after the end of runs.
This is an issue with little impact as I often measure profiles when I have logged in to the lab machine and I can close them by hand but it would be nice to fix it.

**Comment by aspnet-hello** [comment]
We are closing all the issues in this repo because this repo is no longer in used. Please see the README in this repo for more information.
