### ISSUE TITLE
No password on public repo

### ISSUE THREAD

**Issue by shhsu** [aspnet/Performance#157]
Testing the remotedb cold start scenario involving cloning this branch
https://github.com/aspnet/MusicStore/tree/shhsu/coldstart_remote_sql2016

and fetching this file
https://github.com/aspnet/MusicStore/blob/shhsu/coldstart_remote_sql2016/src/MusicStore/config.json

Note that the lab machine is not in REDMOND domain and the password is not re-used anywhere else. However, this could still be a security issue. We should fix it.

**Comment by muratg** [comment]
Consider using UserSecrets functionality

**Comment by shhsu** [comment]
My questions are:

1. can ```dotnet user-secrets set --project ???``` be run even if the project.json does not exist? The automation system would only check out the code when the test is being run and the project cannot be assumed to exist prior to the automation run?

2. I tried to run the application in a published directory and I saw the error 
 error DOTNET1017: Project file does not exist 'D:\publish\MusicStore.core\project.json'

**Comment by shhsu** [comment]
seeing the same error even if I just dotnet run on the source directory

Unhandled Exception: System.InvalidOperationException: Unable to locate a project.json at 'D:\git\aspnet\MusicStore\src\MusicStore\bin\Debug\netcoreapp1.0\'.

**Comment by muratg** [comment]
Yeah both are expected, as we don't carry project.json's with the app anymore. https://github.com/aspnet/UserSecrets/issues/62

We'll need to find another place to store "userSecretsId" key name, though this was punted out of RTM.  In the meantime, you can publish your project.json with the app to get "dotnet run" to work.

Although you should use this only in development scenarios. When running in "production", you should store the secret some other way (one way is using Environment Variables).

**Comment by muratg** [comment]
@shhsu Ping me if you'd like to get more guidance on how to use this in development/production modes.

**Comment by shhsu** [comment]
https://github.com/aspnet/MusicStore/commit/f5eda3da44c4262a0c057aed2f0efe9d0e3cd321

Windows scenario works, still trying to get linux scenario working

**Comment by shhsu** [comment]
OK, it works

I will close the issue and add new instructor to WAVE repro

**Comment by shhsu** [comment]
My code change seem to work. The rest is actually a WAVE issue. I need to open a bug there
