### ISSUE TITLE
Performance Observations for ASP.NET Core Sample Application

### ISSUE THREAD

**Issue by RickStrahl** [aspnet/Performance#158]
As per discussion with Damien yesterday I'm posting a few notes regarding performance comparing a specific project I run across ASP.NET Core MVC 6 and MVC 5.

For this performance test I'm using the following repo on Windows:
- [AlbumViewerVNext](https://github.com/RickStrahl/AlbumViewerVNext)

Project is compiled for Release (-c Release), set to Production enviroment and GcServer mode is set to true.

I'm comparing this to a sample project part of the West Wind Toolkit:
- [Album Viewer Sample](https://github.com/RickStrahl/WestwindToolkit/tree/master/Samples/AlbumViewer)

This is a small sample project that includes API and MVC endpoints for testing as well as some 'HelloWorld' type links.

I'm using [West Wind WebSurge](https://websurge.west-wind.com/) to test both applications locally. The request traces can be found in the `.websurge` files of both projects. Specifically IH look at the `HelloWorld` and `Artist List` and `Static File` requests.

Testing locally on a late model maxed out MBP in Bootcamp. As I'm travelling I don't have an external machine to test with. 

Running 3 tests each for 1 minute and taking the mean value. Results were surprisingly consistent between runs for both platforms with 10 simultaneous threads (optimized for IIS's connection limit).
### Raw Performance

The [HelloWorld endpoint](https://github.com/RickStrahl/AlbumViewerVNext/blob/master/src/AlbumViewerNetCore/Controllers/AlbumViewerApi.cs#L36) performs very well compared to the MVC 5 version.
- **MVC 6**: ~14,500 req/sec
- **MVC 5**: ~11,100 req/sec

This is great.
### EF Core Data Access

Unfortuntately things are not looking so good when I add data access to the mix. Running [a fairly simple Artists data query and result](https://github.com/RickStrahl/AlbumViewerVNext/blob/master/src/AlbumViewerNetCore/Controllers/AlbumViewerApi.cs#L92) out is roughly 20% slower than the MVC 5 code running EF 6.x.
- MVC 6 (sync): ~720 req/sec
- MVC 6 (async): ~825 req/sec
- MVC 5: ~980 req/sec

MVC 5 is faster here by about 15% against the async code, nearly 25% against the sync codtae.

Running the Albums endpoint which is more complex and retrieves much more data I get the following results:
- MVC 6 (sync): ~102 req/sec
- MVC 6 (async): ~75 req/sec
- MVC 5: ~85 req/sec

This looks more on par with EF 6 and in fact is faster in sync mode. The async issue is apparently the reported problem with async queries that using `.include()` which

Single Entity Retrieval:
- MVC 6 (sync): ~1450 req/sec
- MVC 6 (async): ~1245 req/sec
- MVC 5: ~2175 req/sec

Here the MVC 5 code is significantly faster, and again the MVC 6 code in sync operation is a bit faster than the async operation.
### Static File Access

I know ASP.NET Core isn't meant to serve static files, but it looks like static file performance compared to IIS native static file serving is pretty bad.
- IIS: 37,450 req/sec (maxing out 10 connections)
- Kestrel: 5,250 req/sec

Clearly it'll be beneficial to not run static file access through Kestrel if a lot of resources need to be loaded and offload that the front end server.

However, the way that the default setup with ASPNET Core module works today, it's not so simple to route files to IIS - the default configuration routes everything into Kestrel via a wildcard map.

However, there's no easy way to set up what files you **don't** want to pass through. And because the `web.config` that drives requests lives in the content root there's no way to funnel only extensionless URLs into Kestrel with:

``` json
<handlers>
  <add name="aspNetCore" path="*." verb="*" modules="AspNetCoreModule" resourceType="Unspecified" />
</handlers>
```

Now IIS will handle all but extensionless Urls but the base folder doesn't line up now - it's not looking for files in `wwwroot` but in the content root.

If we are to use IIS as a front end, I think this needs addressing.

**Comment by aspnet-hello** [comment]
We are closing all the issues in this repo because this repo is no longer in used. Please see the README in this repo for more information.
