### ISSUE TITLE
Microsoft.AspNetCore.Tests.Throughput tests do not execute

### ISSUE THREAD

**Issue by dougbu** [aspnet/Performance#162]
This project  lacks `"testRunner": "xunit"` and it is therefore ignored during command-line and VS builds. Unfortunately, it doesn't appear automated testing ever worked: The `BasicThroughputTests` constructor contains multiple assertions that fail without unusual environment variables.

**Comment by aspnet-hello** [comment]
We are closing all the issues in this repo because this repo is no longer in used. Please see the README in this repo for more information.
