### ISSUE TITLE
Test Kestrel's ability to handle bursts of new connections being established

### ISSUE THREAD

**Issue by muratg** [aspnet/Performance#165]
_From @halter73 on February 1, 2016 23:8_

Most of Kestrel's benchmarking so far has focused processing requests as quickly as possible on a fixed number of connections (using wrk). We should also test Kestrel's ability to handle bursts of new connections being established and then also disconnecting under high load.

Possibly related: #604

_Copied from original issue: aspnet/KestrelHttpServer#610_

**Comment by muratg** [comment]
_From @benaadams on February 1, 2016 23:25_

This is a good scenario; fast connection churn is a horrible use-case for aspnet4.5+ websockets (due to native pinning); which is mitigated by using pooled buffers. However; Kestrel shouldn't suffer from this (even in websocket scenario); but it does use pinned buffers so it is a good buffer to confirm.

Also connection+disconnection is heavier weight than keep-alive requests.

**Comment by muratg** [comment]
_From @benaadams on February 13, 2016 3:16_

Allocations with 1M non keep-alive connections - load test PR for this https://github.com/aspnet/Performance/pull/48

![no-keepalive-a](http://aoa.blob.core.windows.net/aspnet/no-keepalive-0.png)
![no-keepalive-b](http://aoa.blob.core.windows.net/aspnet/no-keepalive-1.png)
![no-keepalive-c](http://aoa.blob.core.windows.net/aspnet/no-keepalive-2.png)

**Comment by muratg** [comment]
_From @benaadams on February 13, 2016 3:57_

Breaking out System.Object as its very non-specific

![system-object](http://aoa.blob.core.windows.net/aspnet/system-object.png)

**Comment by muratg** [comment]
_From @SajayAntony on February 23, 2016 2:3_

@taoliseki #652 might be related to this. Please keep this on your radar.

**Comment by muratg** [comment]
_From @halter73 on February 29, 2016 20:49_

@mikeharder Not sure you want to take a look at this. It might be better to add these kinds of non-TechEmpower related stress tests/benchmarks to the https://github.com/aspnet/Performance/ repository.

**Comment by muratg** [comment]
_From @SajayAntony on February 29, 2016 20:51_

@mikeharder - specifically this is where the targeted tests are - https://github.com/aspnet/Performance/tree/dev/testapp

**Comment by muratg** [comment]
_From @taoliseki on March 1, 2016 18:22_

The scenario we were measuring from perf side is:
1. Constant load: 10k users with 10k persistent connections and 1 request per 10 seconds per user 
2. Bursty load: 1k users kick in and leave

For the bursty part, 1k WCAT threads were used to disconnect/reconnect per request during a one-hour time window, which resulted in around 3k connection/disconnections per second. I did not see any obvious perf/stress issues (e,g, memory footprint stays stable).  

I did run into some 503 issues at some point. Those issues were fixed by tweaking IIS configurations. You can refer to #652 for more details if you are interested.

**Comment by muratg** [comment]
_From @benaadams on March 2, 2016 6:26_

Probably worth doing some https testing in similar fashion since it is part of the repo.

We did experience memory growth->heavy GC in this area previously (stress testing, not production); but that was prior to the SocketInput memory block release, so hopefully its resolved now.

**Comment by muratg** [comment]
_From @SajayAntony on March 2, 2016 6:51_

Tao could you also provide the memory foot print and how it varied over time. I think @yuwaMSFT has a neat way to capture this over time.

**Comment by muratg** [comment]
_From @yuwaMSFT on March 2, 2016 18:7_

For Windows we can collect memory related perf counters.

For Linux we can use top/atop to get the memory foot print over time.

**Comment by muratg** [comment]
_From @benaadams on March 2, 2016 18:21_

For linux you are probably better using `/proc/xxx` e.g. `/proc/[pid]/status` 

http://www.linuxhowtos.org/manpages/5/proc.htm

**Comment by aspnet-hello** [comment]
We are closing all the issues in this repo because this repo is no longer in used. Please see the README in this repo for more information.
