### ISSUE TITLE
Investigate issues highlighted in Go vs. ASP.NET Core blog post

### ISSUE THREAD

**Issue by DamianEdwards** [aspnet/Performance#174]
https://stefanprodan.com/2016/aspnetcore-vs-golang-data-ingestion-benchmark/?utm_source=golangweekly&utm_medium=email

Can we replicate this set up and attempt to understand any potential performance issues in the scenario or the framework. Some particular things to start:
- The reported issued with Server GC/high memory use (are requests starting to queue up?)
- The use of `dynamic` in the back-end service is likely a bottleneck
- Seems to be a few strings being allocated that could be avoided
- Is `HttpClient` limiting the number of outgoing connections/requests to the back-end process and can it be fixed with configuration
- We've had issues using `ab` to drive load before, RE 1.0/1.1 and keep-alive, maybe that's happening here?
- The manual disposing of the the HTTP responses seem unneeded

**Comment by BrunoMVPCosta** [comment]
I'm very curious about the output of this investigation. This can be a showstopper when trying to make a company adopting the new ASP.NET Core.

Do you think you will work on it in any time soon?

**Comment by mikeharder** [comment]
* [ ] Benchmark Ubuntu 14.04 LTS
* [ ] Benchmark ASP.NET Core app on Windows Server 2016
* [ ] Compare HttpClientSlim to HttpClient

**Comment by adallow** [comment]
What was the outcome of this, where those results correct, can you share your thoughts?

**Comment by aspnet-hello** [comment]
We are closing all the issues in this repo because this repo is no longer in used. Please see the README in this repo for more information.
