### ISSUE TITLE
Investigate startup time on Antares

### ISSUE THREAD

**Issue by rynowak** [aspnet/Performance#175]
We started some investigations of startup time on Antares to determine whether or not the relative cost of the JIT was similar in the Antares (single core, x86, slow network drive) environment to what we had seen on developer boxes (multicore, x64, local drive).

Originally what we measured is that with the Shared Framework and ASP.NET crossgen-ed that JIT time is a much more significant factor of startup (70-80% of CPU time compared to 30-35%). Our analysis leads us to believe that this is an artifact of how we're measuring JIT time in this particular scenario (single-core-VM).

Process CPU time is a measurement of total time the process spent executing code. JIT time is the elapsed time between a start and stop event. This means that if the thread executing the JIT is 'swapped out' while JITting, this time will be attributed to the JIT without the JIT doing any work. This will be common in a single core environment like Antares. 

The only outstanding work here is to run PerfView in this scenario again with _thread time_ instead of _real time_ to determine if the JIT cost is within the similar kind of range that we see in every other environment.

**Comment by rynowak** [comment]
Assigned to @troydai as he's already been driving this

**Comment by Eilon** [comment]
@rynowak please do the needful.

**Comment by rynowak** [comment]
We did this and found nothing super significant here, the JIT is working as intended
