### ISSUE TITLE
Investigate startup time as a whole across common scenarios

### ISSUE THREAD

**Issue by rynowak** [aspnet/Performance#176]
We want to do an investigation to determine the source of delay in the startup time of an ASP.NET Core application. We want to use the aspnet/JITBench flavour of MusicStore as the JIT team has already been using it for investigations.

We should measure the wall clock time from a beginning _user action_ and determine what significant steps take place and how long they take. This adds context any work we do to improve startup and helps us understand what partner asks we might want to make.

We want to assume the ASP.NET binaries will be crossgen-ed since it is our plan to ship them that way ASAP.

Scenarios we want to consider:
- `dotnet .\MusicStore.dll`
- F5 from Visual Studio (build the project)
- CTRL + F5 from Visual Studio
- IIS serving a request from a 'cold' website

**Comment by rynowak** [comment]
Assigned @kichalla since he's already been driving this

**Comment by aspnet-hello** [comment]
We are closing all the issues in this repo because this repo is no longer in used. Please see the README in this repo for more information.
