### ISSUE TITLE
Investigate throughput impact of crossgen

### ISSUE THREAD

**Issue by rynowak** [aspnet/Performance#178]
We need to investigate if/what impact crossgen of the ASP.NET binaries has on runtime throughput. Crossgen (Ready2Run) will eliminate inlining of static call-sites across assembly boundaries.

We need to design a set of experiments that will allow us to determine the impact of this.

**Comment by mikeharder** [comment]
@BrennanConroy: I will work with you to describe the work and help run Benchmarks.

**Comment by mikeharder** [comment]
- [ ] OS: Windows
- [ ] Scenarios: Plaintext, JSON

**Comment by aspnet-hello** [comment]
We are closing all the issues in this repo because this repo is no longer in used. Please see the README in this repo for more information.
