### ISSUE TITLE
Investigate single-request latency

### ISSUE THREAD

**Issue by mikeharder** [aspnet/Performance#182]
The single-request latency of ASP.NET Core is much higher than ASP.NET 4.6:

.NET | Environment | GET (ms) | POST (ms)
--- | --- | --- | ---
Framework | Localhost | 3.33 | 3.57
Core | Localhost | 5.00 | 5.40
Framework | Azure | 6.19 | 6.11
Core | Azure | 13.50 | 10.69

Repro here: https://github.com/mikeharder/AspNetLatency

**Comment by davidfowl** [comment]
Interesting

**Comment by davidfowl** [comment]
Why are you doing synchronous reads and writes?

**Comment by mikeharder** [comment]
The original repro used sync writes, at least for the Framework case.  And I assumed sync would have lower latency which it usually does for single-request tests.  I will compare to async.

**Comment by mikeharder** [comment]
Console logging was enabled for the Core application, which adds considerable latency.  Filed issue to consider reducing console logger latency: https://github.com/aspnet/Logging/issues/515

With logging disabled, or using serilog to write to a file (https://github.com/aspnet/Logging/issues/441#issuecomment-254405907), latency is about the same between Core and Framework.
