### ISSUE TITLE
Add E2E scenario test: Resource Provider

### ISSUE THREAD

**Issue by rynowak** [aspnet/Performance#185]
We want to work with the the cache team to get usage and frequency data about their RP
  - Usage patterns
  - Frequency of various HTTP endpoints being called
  - General shape of API
  - Data Sizes

Then, we want to turn this into an end to end test for the full stack

**Comment by aspnet-hello** [comment]
We are closing all the issues in this repo because this repo is no longer in used. Please see the README in this repo for more information.
