### ISSUE TITLE
Measure throughput without reusing connections

### ISSUE THREAD

**Issue by mikeharder** [aspnet/Performance#196]
Our existing thoughput tests execute many requests over a small number of long-lived connections.  We should also test clients which execute one request per connection, to measure the overhead of establishing connections.  This is especially important when using HTTPS.

It should be sufficient to test a single scenario without pipelining, like JSON (both HTTP and HTTPS).

A challenge with short-lived connections is port exhaustion.  We might be able to mitigate this by having the server listen on many ports, since client ports can be reused if the server port is different.

**Comment by aspnet-hello** [comment]
We are closing all the issues in this repo because this repo is no longer in used. Please see the README in this repo for more information.
