### ISSUE TITLE
Compare PostgreSQL with Npgsql against Microsoft SQL Server

### ISSUE THREAD

**Issue by mikeharder** [aspnet/Performance#201]
Compare the performance of PostgreSQL with Npgsql against Microsoft SQL Server, using our TechEmpower scenarios.

**Comment by roji** [comment]
Just as a reminder, don't forget to turn on Npgsql automatic preparation when benchmarking Entity Framework. It's also recommended to set `No Reset On Close` for all scenarios.

**Comment by aspnet-hello** [comment]
We are closing all the issues in this repo because this repo is no longer in used. Please see the README in this repo for more information.
