### ISSUE TITLE
Remove workaround for dotnet/core-setup#1221

### ISSUE THREAD

**Issue by dougbu** [aspnet/Performance#204]
Commit 7548775 adds a workaround for dotnet/core-setup#1221. Currently cannot load the test assembly without this. Once the external bug is fixed, revert this commit.

See similar "should be reverted" bugs for the same issue: aspnet/Entropy#186 and aspnet/Localization#310.

**Comment by aspnet-hello** [comment]
We are closing all the issues in this repo because this repo is no longer in used. Please see the README in this repo for more information.
