### ISSUE TITLE
Follow up on conversion to MSBuild project system

### ISSUE THREAD

**Issue by dougbu** [aspnet/Performance#207]
Commit 92e0deb left a few rough edges and untested area that we should address relatively soon:
- fix xplat failures of the `stress-test` target
  - .NET 4.5.1 stress tests attempt to run on Linux and fail
  ```
  EXEC : warning : The path '/home/dougbu/src/Performance/stress-test/Microsoft.AspNetCore.Tests.Stress/bin/Debug/net451' specified in the 'TestAdapterPath' does not contain any test adapters, provide a valid path and try again. [/home/dougbu/src/Performance/.build/makefile.proj]
  EXEC : warning : No test is available in /home/dougbu/src/Performance/stress-test/Microsoft.AspNetCore.Tests.Stress/bin/Debug/netcoreapp1.1/Microsoft.AspNetCore.Tests.Stress.dll. Make sure that installed test discoverers & executors, platform & framework version settings are appropriate and try again. [/home/dougbu/src/Performance/.build/makefile.proj]
  ```
  - .NET Core tests attempt to run full desktop servers and those depployments fail
  ```
  fail: StarterMvc.StarterMvc.CoreCLR[0]
        run-detectors: unable to find an interpreter for /home/dougbu/src/Performance/testapp/StarterMvc/bin/Debug/net451/StarterMvc.exe
  ```
- fix web site execution in IIS; definitely need more `UseIISIntegration()` calls
  - some sites work but many do not start up correctly
- test and (if necessary) fix additional .sln files in this repo
  - seem fine but haven't tested everything about the legacy projects e.g. upload in the legacy MultipartPOST project
- test and (if necessary) fix the Antares-related tests
- double-check all web sites when started from command line
- debug / work around odd Output Window messages when loading Performance.sln in VS2017 e.g.
  ```
  Error occurred while restoring NuGet packages: The operation failed as details for project HelloWorldMvc could not be loaded.
  ```

**Comment by dougbu** [comment]
Noticed the first couple of items in the list above while converting to MSBuild project system. But, they were likely problems before then.

**Comment by aspnet-hello** [comment]
We are closing all the issues in this repo because this repo is no longer in used. Please see the README in this repo for more information.
