### ISSUE TITLE
Investigate performance of Post in Kestrel

### ISSUE THREAD

**Issue by muratg** [aspnet/Performance#212]
See: https://github.com/aspnet/KestrelHttpServer/issues/1319

**Comment by gulbanana** [comment]
from that issue - i have a reliable but complex repro where kestrel POST is extremely slow to read the request body. performance is fine in behind iis express in visual studio.

i've tracked it down to this point:
`Request.Body.CopyToAsync(new MemoryStream())`
takes a fixed ~160ms when running kestrel under netcoreapp2.0 in azure app service. 

here's the body of the request, which is a multipart form with two short parameters - but i'm not running any of the form-reading code, just copying the body as bytes.
```
--2656bd3f-7235-4f66-a798-da397838cd2f
Content-Type: text/plain; charset=utf-8
Content-Disposition: form-data; name=format

Xml
--2656bd3f-7235-4f66-a798-da397838cd2f
Content-Type: text/plain; charset=utf-8
Content-Disposition: form-data; name=ticket

<Ticket xmlns:i="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://schemas.datacontract.org/2004/07/The.Security"><Subject><Name>user</Name><Realm>pbkdf</Realm></Subject><Token i:nil="true" /></Ticket>
--2656bd3f-7235-4f66-a798-da397838cd2f--
```

**Comment by aspnet-hello** [comment]
We are closing all the issues in this repo because this repo is no longer in used. Please see the README in this repo for more information.
