### ISSUE TITLE
Do performance run for May 2017 patch release

### ISSUE THREAD

**Issue by DamianEdwards** [aspnet/Performance#224]
Compare following scenarios for 1.0.0 & 1.1.0, 1.0.4 & 1.1.1, and 1.0.5 & 1.1.2
Get RPS, latency, and error rate:
- TechEmpower Plaintext
- TechEmpower JSON
- TechEmpower Fortunes

**Comment by dougbu** [comment]
Will fill in the blanks:

| | scenario | URL path | CPU% | RPS | latency | errors | timeouts |
| ----- | -------- | -------- | -------- | -------- | -------- | -------- | -------- |
| 1.0.0 | plaintext | /plaintext | | | | | |
| 1.0.4 | plaintext | /plaintext | | | | | |
| 1.0.5 | plaintext | /plaintext | | | | | |
| 1.1.0 | plaintext | /plaintext | | | | | |
| 1.1.2 | plaintext | /plaintext | | | | | |
| 1.1.3 | plaintext | /plaintext | | | | | |
| 1.0.0 | json | /json | | | | | |
| 1.0.4 | json | /json | | | | | |
| 1.0.5 | json | /json | | | | | |
| 1.1.0 | json | /json | | | | | |
| 1.1.2 | json | /json | | | | | |
| 1.1.3 | json | /json | | | | | |
| 1.0.0 | MvcDbFortunesEf | /mvc/fortunes/ef | | | | | |
| 1.0.4 | MvcDbFortunesEf | /mvc/fortunes/ef | | | | | |
| 1.0.5 | MvcDbFortunesEf | /mvc/fortunes/ef | | | | | |
| 1.1.0 | MvcDbFortunesEf | /mvc/fortunes/ef | | | | | |
| 1.1.2 | MvcDbFortunesEf | /mvc/fortunes/ef | | | | | |
| 1.1.3 | MvcDbFortunesEf | /mvc/fortunes/ef | | | | | |

**Comment by dougbu** [comment]
Updated table after adjusting system settings and enabling HTTP pipelines:

| Version | Scenario | URL | RPS | % original | CPU | latency (ms) | timeouts |
| ---- | ---- | ---- | ---- | ---- | ---- | ---- | ---- |
| 1.0.0 | plaintext | /plaintext | 1109665.58 | 100.00% | 69.20 | 5.17 | 3043 |
| 1.0.4 | plaintext | /plaintext | 1130025.27 | 101.83% | 69.40 | 5.21 | 804 |
| 1.0.5 | plaintext | /plaintext | 1152641.98 | 103.87% | 73.25 | 5.88 | 1269 |
| 1.1.0 | plaintext | /plaintext | 1192604.02 | 107.47% | 67.15 | 4.96 | 1411 |
| 1.1.2 | plaintext | /plaintext | 1175686.33 | 105.95% | 69.05 | 5.13 | 1348 |
| 1.1.3 | plaintext | /plaintext | 1195924.75 | 107.77% | 69.00 | 5.69 | 1441 |
| 1.0.0 | json | /json | 824388.90 | 100.00% | 96.50 | 6.57 | 3010 |
| 1.0.4 | json | /json | 798602.76 | 96.87% | 96.40 | 6.73 | 507 |
| 1.0.5 | json | /json | 776245.85 | 94.16% | 97.20 | 6.93 | 693 |
| 1.1.0 | json | /json | 819822.30 | 99.45% | 97.30 | 6.48 | 1289 |
| 1.1.2 | json | /json | 824975.86 | 100.07% | 97.10 | 6.51 | 1455 |
| 1.1.3 | json | /json | 789828.53 | 95.81% | 97.00 | 6.74 | 1455 |
| 1.0.0 | MvcDbFortunesEf | /mvc/fortunes/ef | 17596.30 | 100.00% | 86.10 | 151.47 | 0 |
| 1.0.4 | MvcDbFortunesEf | /mvc/fortunes/ef | 17402.40 | 98.90% | 84.30 | 123.79 | 0 |
| 1.0.5 | MvcDbFortunesEf | /mvc/fortunes/ef | 17597.12 | 100.00% | 81.50 | 115.31 | 0 |
| 1.1.0 | MvcDbFortunesEf | /mvc/fortunes/ef | 16844.30 | 95.73% | 84.35 | 125.84 | 0 |
| 1.1.2 | MvcDbFortunesEf | /mvc/fortunes/ef | 16704.97 | 94.93% | 82.55 | 121.21 | 0 |
| 1.1.3 | MvcDbFortunesEf | /mvc/fortunes/ef | 17302.89 | 98.33% | 84.55 | 140.39 | 0 |

**Comment by dougbu** [comment]
Latest RPS numbers, now with 2.0.0-preview1:

| Version | Scenario | RPS | % original |
| ---- | ---- | ---- | ---- |
| 1.0.0 | plaintext | 481691.89 | 100.00% |
| 1.0.4 | plaintext | 474618.77 | 98.53% |
| 1.0.5 | plaintext | 486057.12 | 100.91% |
| 1.1.0 | plaintext | 428303.46 | 88.92% |
| 1.1.2 | plaintext | 438930.29 | 91.12% |
| 1.1.3 | plaintext | 430435.48 | 89.36% |
| 2.0.0-preview1 | plaintext | 499027.00 | 103.60% |
| 1.0.0 | json | 133845.36 | 100.00% |
| 1.0.4 | json | 130627.01 | 97.60% |
| 1.0.5 | json | 145004.16 | 108.34% |
| 1.1.0 | json | 109818.76 | 82.05% |
| 1.1.2 | json | 116400.29 | 86.97% |
| 1.1.3 | json | 119109.08 | 88.99% |
| 2.0.0-preview1 | json | 148788.43 | 111.16% |
| 1.0.0 | MvcDbFortunesEf | 234019.75 | 100.00% |
| 1.0.4 | MvcDbFortunesEf | 238864.50 | 102.07% |
| 1.0.5 | MvcDbFortunesEf | 238098.00 | 101.74% |
| 1.1.0 | MvcDbFortunesEf | 237849.00 | 101.64% |
| 1.1.2 | MvcDbFortunesEf | 238600.25 | 101.96% |
| 1.1.3 | MvcDbFortunesEf | 239467.00 | 102.33% |
| 2.0.0-preview1 | MvcDbFortunesEf | 279899.00 | 119.60% |
