### ISSUE TITLE
Get perf baseline for all middleware when in pipeline but request is passed through (no-op)

### ISSUE THREAD

**Issue by DamianEdwards** [aspnet/Performance#225]
Get perf regression from baseline of TechEmpower Plaintext, which each of the following middleware in the pipeline (by itself) running in no-op/pass-through mode:
- ExceptionHandler
- Rewrite
- Authentication
- StaticFiles
- Routing
- WebSockets
- ResponseCaching
- Session
- ResponseCompression
- CORS
- Localization

**Comment by DamianEdwards** [comment]
@mikeharder can you update the infrastructure to support this in a way you like

**Comment by natemcmaster** [comment]
_Engineering triage decision:_ this does not appear to be high priority, and we do not plan to address this.
