### ISSUE TITLE
Further optimize TechEmpower database scenarios

### ISSUE THREAD

**Issue by dougbu** [aspnet/Performance#236]
After we submit aspnet/FrameworkBenchmarks#3 to TechEmpower, we likely have further low-hanging fruit for optimizing database scenarios. Some thoughts:
- What is the best `MaxBatchSize()` value for the MvcDbFortunesEf scenairo? Do we need to override the default at all?
  - Either way, remove the `_useBatchUpdates` hack from `EfDb` -- just remove it or replace it with a `MaxBatchSize()` call.
- Check suggestions on http://www.npgsql.org/doc/performance.html e.g. should Postgres connection strings include a `Max Auto Prepare` setting?

**Comment by aspnet-hello** [comment]
We are closing all the issues in this repo because this repo is no longer in used. Please see the README in this repo for more information.
