### ISSUE TITLE
Inner loop performance improvements

### ISSUE THREAD

**Issue by glennc** [aspnet/Performance#249]
Inner Loop: The loop that spans ideation* through code commit, and most often centers on an engineer writing the code for a given feature. Because engineers require an idea from which to design and build a feature, this loop also includes prototyping, crowd-sourced feature engagement and feasibility studies.
*Yes, ideation is a word and I learnt it when finding this definition

Outer Loop: This is the loop that gets committed code out to Production. Because a feature is not really finished until we have successfully navigated live user trials, our experimentation-centered culture requires that we consider the cost of flighting features within this loop.

In our case, inner-loop is mostly focused on "change code, see changes in browser or make request and get result". We want that cycle to be as fast as possible and will be investing a large amount of engineering effort in 2.1 to make that happen.

**Comment by DamianEdwards** [comment]
I think it's safe to close this for 2.1 now.
