### ISSUE TITLE
Implement the TechEmpower Benchmarks

### ISSUE THREAD

**Issue by SajayAntony** [aspnet/Performance#28]
We currently don't have ASPNET Core running on the TechEmpower benchmarks. This needs to be implemented.

**Comment by muratg** [comment]
https://github.com/aspnet/Benchmarks could be a good starting point. Make sure to sync up with @DamianEdwards too as he has a lot of context on this.

**Comment by SajayAntony** [comment]
PR - TechEmpower/FrameworkBenchmarks#2079

**Comment by mikeharder** [comment]
I assume this is done.
