### ISSUE TITLE
Automatic install of repository dependencies

### ISSUE THREAD

**Issue by DavidObando** [aspnet/Performance#32]
The performance tests depend on bower and gulp but there's no evidence of these dependencies being installed by the build process or the test run process. Both bower and gulp are installed via npm, which makes npm another dependency.

We need to list these and any other dependencies and automate their installation.

Note that in my system I got a lot of errors because I didn't have gulp or bower, and they didn't go away until I manually installed them.

**Comment by SajayAntony** [comment]
I noticed this too. 
Could you append this info to the Readme and send out a PR with murat as CC. 
@muratg

**Comment by muratg** [comment]
:+1:

**Comment by DavidObando** [comment]
@SajayAntony sent the PR for the documentation, but I'm leaving this bug open as automation for this is possible and not too expensive.

**Comment by DavidObando** [comment]
Note: investigate if this can be done by adding the dependencies to `dashboard\PerformanceDashboard\package.json`.

**Comment by aspnet-hello** [comment]
We are closing all the issues in this repo because this repo is no longer in used. Please see the README in this repo for more information.
