### ISSUE TITLE
Build using a CI and add a build health badge to README.md

### ISSUE THREAD

**Issue by DavidObando** [aspnet/Performance#33]
Consider using Travis (like [Entity Framework](https://github.com/aspnet/EntityFramework)) or Jenkins (like [cli](https://github.com/dotnet/cli)). We should keep a very high quality bar on the health status of this repository.

**Comment by Eilon** [comment]
I can enable Travis and AppVeyor for this repo if needed - but they can't write to the repo, they are read-only. Our internal CI can push updates/status/reports to somewhere (but probably not the README.md file, as it will generate a lot of noise).

**Comment by Eilon** [comment]
Or we can use the badges like we do in all the other repos (see the readme of any other repo).

**Comment by DavidObando** [comment]
Yup, the badges is what I had in mind. Sorry for not being more specific.

**Comment by Eilon** [comment]
Ah ok. I'll enable Travis and AppVeyor.

**Comment by Eilon** [comment]
Re-opening because all I did was *enable* Travis and AppVeyor. We need to actually have scripts here to run them, e.g. https://github.com/aspnet/Mvc/blob/dev/appveyor.yml and https://github.com/aspnet/Mvc/blob/dev/.travis.yml.

**Comment by DavidObando** [comment]
Thanks sir!

**Comment by DavidObando** [comment]
Hi @Eilon, can you check if Appveyor is enabled for the Performance repository? I get an error message: `Build not found or access denied`.

**Comment by Eilon** [comment]
I'll just take a look, no need to assign...

**Comment by Eilon** [comment]
AppVeyor was definitely set up, so I'm not sure why it wasn't building PRs. I just forced AppVeyor to do a build on its own, maybe that'll wake it up or something...

**Comment by DavidObando** [comment]
Thanks @Eilon. I did see it running once after you forced it (it now reports a status and all), but it doesn't appear to be picking up changes.

**Comment by Eilon** [comment]
I recreated the AppVeyor project but it seems to be a bit finicky at the moment. Let's give it another day or two.

**Comment by DavidObando** [comment]
Closing as resolved. AppVeyor is now running. It seems to be having trouble building but that may be expected at this point. I'll open a new issue if the builds don't pass when expected to.

**Comment by Eilon** [comment]
@DavidObando ah ok good. Mark this as 3-Done then?
