### ISSUE TITLE
Fix build break caused by absence of preserveCompilationContext

### ISSUE THREAD

**Issue by DavidObando** [aspnet/Performance#42]
After the move to CLI a lot of projects are failing to build with:
```
System.InvalidOperationException : Entry assembly was compiled without `preserveCompilationContext` enabled
```
The fix is to set that flag to true in project.json in the compilationOptions node.

**Comment by DavidObando** [comment]
This is caused by a CLI issue [dotnet/cli#1303](https://github.com/dotnet/cli/issues/1303). We can keep this bug for tracking purposes.

**Comment by JunTaoLuo** [comment]
Since you have #44 tracking this, consider closing as dup?

**Comment by DavidObando** [comment]
Closing as dup of #44.
