### ISSUE TITLE
Tracking bug of CLI issues affecting the Performance repository

### ISSUE THREAD

**Issue by DavidObando** [aspnet/Performance#44]
**PRI 1**
  * ~~dotnet/cli#1303 - blocks execution of performance tests when using CLI.~~
  * ~~dotnet/cli#1304 - blocks execution of performance tests and dashboard when using CLI.~~
  * ~~aspnet/Universe#384 - blocks package restore in non-Windows environments. (Also check dotnet/cli#1372)~~
  * ~~dotnet/coreclr#3101 - segfault during compile time in Ubuntu (dotnet has exit code 139)~~

**PRI 2**
  * dotnet/cli#1336 - affects execution of dashboard project when using CLI.
  * dotnet/cli#809 - affects package restore on OSX

Please expand as appropriate.

**Comment by JunTaoLuo** [comment]
I've also ran into https://github.com/dotnet/cli/issues/1304

**Comment by muratg** [comment]
@danroth27

**Comment by DavidObando** [comment]
We're no longer blocked by these. Closing.
