### ISSUE TITLE
Will *nix continue requiring mono in order to build?

### ISSUE THREAD

**Issue by DavidObando** [aspnet/Performance#47]
Just wondering if we have planned to remove this dependency.

**Comment by moozzyk** [comment]
https://github.com/aspnet/Universe/issues/377

**Comment by DavidObando** [comment]
:+1:

**Comment by SajayAntony** [comment]
Is this still the case?

**Comment by moozzyk** [comment]
This item can be closed. As per the related issue we want to continue to run tests on Mono so we can't remove this dependency.
