### ISSUE TITLE
Memory Allocation Analysis for MVC TagHelpers for generating form

### ISSUE THREAD

**Issue by mnltejaswini** [aspnet/Performance#57]
Using BasicViews MVC app, collect the memory allocation profile for built in tag helpers to generate View that has form. Identify optimizations. Discussed with Ryan and Taylor and we prioritized the following items

1.  Reduce Allocations in Get Virtual Path that is used for URL generation in the TagHelpers
2. Understand and reduce the allocations in Create Model Expression  that is used for asp-for attribute
3. Pool Tag Helper Context Items 
Razor\src\Microsoft.AspNetCore.Razor.Runtime\Runtime\TagHelpers\TagHelperScopeManager.Begin()
```
if (_executionScopes.Count > 0)
            {
                items = new CopyOnWriteDictionary<object, object>(
                    _executionScopes.Peek().Items,
                    comparer: EqualityComparer<object>.Default);
            }
            else
            {
                items = new Dictionary<object, object>();
            }
```

We allocate Dictionary for items irrespective of the tag helper uses it or not. Make this allocation lazy 
4. Set Content - Known issue looged under MVC https://github.com/aspnet/Razor/issues/621 
5. ErrorsOrder

          {
                var metadata = viewData.ModelMetadata;     
           var orderer = new ErrorsOrderer(metadata);
                return viewData.ModelState
                    .OrderBy(data => orderer.GetOrder(data.Key))
                    .Select(ms => ms.Value);
            }
ErrorsOrder creates a dictionary which can be optimized.

**Comment by dougbu** [comment]
FYI the Perf labels in [MVC](https://github.com/aspnet/Mvc/issues?q=is%3Aopen+is%3Aissue+label%3APerf) and [Razor](https://github.com/aspnet/Razor/issues?q=is%3Aopen+is%3Aissue+label%3APerf) contain issues found using this app and others (now) in this repo.

For example, the After picture for aspnet/Antiforgery#56 (the only issue in that repo with the Perf label) looks like:
![249a7442-d49c-11e5-8712-42728bc2b808](https://cloud.githubusercontent.com/assets/6431421/13126527/a3bdc902-d57f-11e5-84a7-e2bef46c6074.png)

**Comment by SajayAntony** [comment]
@dougbu thanks. I'm consolidating this across all the repo's.

**Comment by mnltejaswini** [comment]
Reduce Allocations in Get Virtual Path that is used for URL generation in the TagHelpers (A separate analysis will be done for the attribute routing. Currently these optimizations are applicable to the Path routing)
Optimizations in MVC repo
------------------------------------
1.Currently we create a new UrlHelper for every action URL that has to be resolved on a view. We will have single URL helper per context. This will save allocations on a view that has multiple action URLs.
2. Also, URLHelperFactory will maintain a pool of StringBuilders that will be used by URL Helpers to generate URLs. 

 These optimizations will save 'n' allocations of URL Helpers for a view with 'n' Links. Also, it saves lots of StringBuilder objects that are frequently used to build a URL path

Pull request corresponding to these changes: Pending

Optimizations in Routing repo
--------------------------------------
3.We create a new RouteValueDictionary() for “CombinedValues”.  I am assuming that in most cases , CombinedValues doesn’t have more than AcceptedValues. In such cases, we can avoid this allocation and have CombinedValues same as AcceptedValues
4.	Avoid creating Enumerator if there aren’t any constraints in RouteConstraintsMatcher
5.Lazy create List<LinkGenerationMatch> in GetMatches.of TemplateBinder. 

 These optimizations save around ~7 allocations per request that generates an action URL.  

Pull request corresponding to these changes : https://github.com/aspnet/Routing/pull/288

**Comment by mnltejaswini** [comment]
Pull request for Routing repo is merged and closed.
New pull request for MVC repo is https://github.com/aspnet/Mvc/pull/4151

**Comment by mnltejaswini** [comment]
Attribute Routing
----------------------
TreeRouter.GenerateVirtualPath() has the following expression

var parameter = entry.Template.Parameters
 .FirstOrDefault(p => string.Equals(p.Name, kvp.Key, StringComparison.OrdinalIgnoreCase));

that is resulting in 3 allocations
 1. Delegate for FirstOrDefault (System.Func)
 2. Closure for TreeRouter
 3. Enumerator for Parameters 
 This expression is used in a loop for each of the Route values. 

By removing this Linq expression, there is 3.5% saving in total number of allocations and 2.5% in total number of bytes allocated. 

The measurements are against Performance/BasicViews test app with the View having 6 action links . Each of these actions href is generated using TagHelpers with attribute routing. And loadtest is run against the app with the following setting

loadtest --rps 100 -n 3000 -k 

Pull request against Routing app https://github.com/aspnet/Routing/pull/290

**Comment by mnltejaswini** [comment]
The only item remaining under this issue is related to ErrorsOrder class. AS per the current MVC repo, this class no longer exists. All other fixes proposed in this issue are done and hence closing this issue.
