### ISSUE TITLE
Implement a stress test for POST with large multipart forms

### ISSUE THREAD

**Issue by DavidObando** [aspnet/Performance#58]
We want to track different metrics like - Memory/Latency distribution for a particular operation with the follow mix.
```
1. Small text part + large text part: 10MB/100MB/1GB [5:3:1]
2. Small text part + large binary part: 10MB/100MB/1GB [5:3:1]
3. A number of large parts: text/binary [2:1] totalling more than 4GB (to test 32-bit limit)
```
  * No-auth middleware scenario initially and can be done as enhancements.
  * Small text part can be a simple JSON message
  * Payload must be generated dynamically, if possible. We don't want to check-in large files here, or depend on large blobs elsewhere.
  * If possible, test multipart to memory in addition to multipart to disk.

**Comment by DavidObando** [comment]
Currently blocked by #62.

/cc @SajayAntony

**Comment by SajayAntony** [comment]
As discussed we should be able to roll this upto MusicStore as an `Addon`
