### ISSUE TITLE
Music store perf/stress covering E2E scenarios

### ISSUE THREAD

**Issue by sajayantony** [aspnet/Performance#68]
The aim is to cover a large numbers of code paths, focusing on stress. 
These items will be marked complete once we them validated and the commit done to this repo. 
/cc @sivagms @martinpf 
## Services
- [ ] ConfigBuilder
- [ ] EntityFramework (with SQL Server localdb)
- [ ] In Memory Caching
- [ ] CORS
- [ ] Session Management
- [ ] Static Files
- [ ] Authorization (user name / pwd) (uses UserManager  and SigninManager to handle Auth)
- [ ] Authorization (Open Id Connect / OAuth) (not used by default)  Do we need  coverage for this?
- [ ] Authorization (ntlm) (not used by default)
## Features
- [ ] Routing
- [ ] [Area] on controller used in routing.
- [ ] [Authorize] on certain controllers
- [ ] Dependency Injection [FromServices] on controller ctor parameters
- [ ] Dependency Injection [FromServices] on action parameters
- [ ] [FromForm] on action parameters
- [ ] CancellationToken on action parameters (they are passed to EF calls)
- [ ] [ValidateAntiForgeryToken]
- [ ] ViewComponents
- [ ] HTML Helpers (is there a list we should cover?)
- [ ] Injecting Services (@Inject) into Views
- [ ] Async methods  (@await Html.PartialAsync for example)
- [ ] Razor Logic (@if, @foreach)      Is there a set we should cover?
- [ ] Tag Helpers (is there a set we should cover?)
- [ ] Error paths - 404s, Bad requests etc.
## Missing Features / Attributes
- [ ] FileServer
- [ ] Diagnostics / logging
- [ ] Custom DependencyInjection
- [ ] ResponseCaching
- [ ] Request Features (context.GetFeature() )
- [ ] Validation Attributes
- [ ] WebAPI 
- [ ] Large / Complex Views  Do we need to cover large views?
- [ ] Large / Complex EF Queries

**Comment by aspnet-hello** [comment]
We are closing all the issues in this repo because this repo is no longer in used. Please see the README in this repo for more information.
