### ISSUE TITLE
Add baseline and benchmark for webapi. 

### ISSUE THREAD

**Issue by sajayantony** [aspnet/Performance#69]

**Comment by SajayAntony** [comment]
Assigning to Nathan to light this up in the perf lab to compare with Netty. 
Basically we want to see 2 things. 

1. WebAPI returning json
2. MVC

**Comment by SajayAntony** [comment]
@nathana1 has this been added to the benchmarks repo?

**Comment by nathana1** [comment]
Yes, these are in benchmarks.

**Comment by aspnet-hello** [comment]
We are closing all the issues in this repo because this repo is no longer in used. Please see the README in this repo for more information.
