### ISSUE TITLE
Check status of test Microsoft.AspNetCore.Tests.Throughput

### ISSUE THREAD

**Issue by DavidObando** [aspnet/Performance#74]
It seems to be outdated and not running during build. Check its validity, health and if viable enable to run with the other tests.

**Comment by SajayAntony** [comment]
Thanks for taking care of this. We need to have this running back again.
/cc @troydai do you why these stopped?

**Comment by troydai** [comment]
It is set to run 4 times per-day. I didn't make any changes to perf-teamcity2.
