### ISSUE TITLE
Optimize Cold Start

### ISSUE THREAD

**Issue by sajayantony** [aspnet/Performance#75]
The cold start on linux is currently about 9.6 seconds on Linx and upto 10 seconds on windows 
Here are a list of blocking issues that needs to be resolved to bring down the time for cold start 
- [ ] Enable application crossgen on app publish
- [ ] Enable package cache crossgen
- [ ] Enable view precompilation. 

/cc @davidfowl @brianrob @shhsu

**Comment by davidfowl** [comment]
@SajayAntony Are you using DNX or the CLI?

**Comment by shhsu** [comment]
I am using cli

**Comment by SajayAntony** [comment]
Identical hardware for windows and Linux has been setup for Cold Start. We are currently measuring on SSD's. Basically this will be used to track regressions as well.

**Comment by brianrob** [comment]
Do we believe that all of this work needs to be done in aspnet, or that some of it should be part of the CLI?  I could believe that everything except for view pre-compilation could be done in the CLI.

**Comment by davidfowl** [comment]
Some of these require CLI features others don't. We're working on the shared framework story where that will always be crossgen'd. The other scenario is for standalone apps, which is all we have at this very moment. For those, we want to add a `--crossgen` flag to publish in the CLI to enable crossgen of the standalone applications.

The cache is a separate thing that can be done by us. We did it before for azure websites, we can do it again.

View precompilation is on us as well.

**Comment by davidfowl** [comment]
There's also the question of how we should be doing IBC this time around. Before we used to do it all but i don't think we wanted to do that going forward.

/cc @troydai since he did most of the IBC work previously

**Comment by brianrob** [comment]
Is there a reason that we wouldn't crossgen by default even for standalone apps?  The cost on coldstart of JIT compilation is significant.  We already make is a requirement for mscorlib by shipping its native image OOB.  I'd like to say that we crossgen as much as we can by default, and choose not to when things like size on disk become a blocker (and I'm not sure that it would be).

**Comment by brianrob** [comment]
I think we should do the measurements and find out.  The size will be bigger for sure - but there's also a question of whether or not we need to actually ship the IL assemblies along with the native images.  The IL is duplicated in the native images and so that's where you're guaranteed 2X.

In any case, I think we should see the data before we pick a default.

**Comment by aspnet-hello** [comment]
We are closing all the issues in this repo because this repo is no longer in used. Please see the README in this repo for more information.
